### ISSUE TITLE
Occasional IT error `Cannot create preexisting table`

### ISSUE THREAD

**Issue by googley42** [zio/zio-dynamodb#96]
We sometime get the below error for IT tests where we create and delete tables per tests. My hunch is that table creation is async.
```
[info]         ╠─A checked error was not handled.
[info]         ║ software.amazon.awssdk.services.dynamodb.model.ResourceInUseException: Cannot create preexisting table (Service: DynamoDb, Status Code: 400, Request ID: 5bc27eed-8a2c-4a52-a1c3-1055dff68cd9, Extended Request ID: null)
[info]         ║ 	at software.amazon.awssdk.services.dynamodb.model.ResourceInUseException$BuilderImpl.build(ResourceInUseException.java:118)
[info]         ║ 	at software.amazon.awssdk.services.dynamodb.model.ResourceInUseException$BuilderImpl.build(ResourceInUseException.java:78)
```

**Comment by googley42** [comment]
closing as I have not seen this in a while
